"""Mapa de apelidos → nome canônico (após `normalize`, i.e. sem acento, minúsculo).

Resolve o que a normalização sozinha não pega: casas exibindo nomes em inglês vs
português. Foco inicial: seleções da Copa do Mundo 2026. Cresça este mapa observando
os "near-misses" logados pelo matcher (ratio entre 70 e o threshold).
"""

ALIAS_MAP: dict[str, str] = {
    # seleções — inglês/variações → canônico (pt, sem acento)
    "brazil": "brasil",
    "germany": "alemanha",
    "deutschland": "alemanha",
    "mexico": "mexico",
    "usa": "estados unidos",
    "united states": "estados unidos",
    "estados unidos da america": "estados unidos",
    "netherlands": "holanda",
    "paises baixos": "holanda",
    "england": "inglaterra",
    "spain": "espanha",
    "france": "franca",
    "japan": "japao",
    "south korea": "coreia do sul",
    "korea republic": "coreia do sul",
    "republica da coreia": "coreia do sul",
    "ivory coast": "costa do marfim",
    "cote d ivoire": "costa do marfim",  # forma pós-normalização (pontuação removida)
    "cote divoire": "costa do marfim",
    "switzerland": "suica",
    "belgium": "belgica",
    "croatia": "croacia",
    "morocco": "marrocos",
    "iran": "ira",
    "ir iran": "ira",
    "saudi arabia": "arabia saudita",
    "ecuador": "equador",
    "uruguay": "uruguai",
    "paraguay": "paraguai",
    "italy": "italia",
    "norway": "noruega",
    "scotland": "escocia",
    "wales": "pais de gales",
    "new zealand": "nova zelandia",
    "egypt": "egito",
    "south africa": "africa do sul",
    "algeria": "argelia",
    "ghana": "gana",
    "cameroon": "camaroes",
    "qatar": "catar",
    "jordan": "jordania",
    "uzbekistan": "uzbequistao",
    "cape verde": "cabo verde",
    "turkey": "turquia",
    "turkiye": "turquia",
    "austria": "austria",
    "poland": "polonia",
    "portugal": "portugal",
    "canada": "canada",
    "colombia": "colombia",
    "argentina": "argentina",
    "australia": "australia",
    "senegal": "senegal",
    "nigeria": "nigeria",
    "tunisia": "tunisia",
    "panama": "panama",
    "haiti": "haiti",
    "curacao": "curacao",
    "honduras": "honduras",
    # clubes brasileiros (exemplos p/ expansão futura a campeonatos de clubes)
    "spfc": "sao paulo",
    "sao paulo fc": "sao paulo",
    "athletico pr": "athletico paranaense",
    "atletico mg": "atletico mineiro",
    "vasco da gama": "vasco",
}
